name: intellectual_property
statutes:
  - Patents Act, 1970
  - Trade Marks Act, 1999
terminology:
  - prior art
  - infringement
  - passing off
reasoning_patterns:
  - Assess originality and registrability.
  - Compare marks or inventions for substantial similarity.
